{
	"version": 1734321593,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/gambarremovebgpreview-sheet0.png",
		"images/label_namaremovebgpreview-sheet0.png",
		"images/n-sheet0.png",
		"images/bgtebakpahlawan-sheet0.png",
		"images/bglayout1-sheet0.png",
		"images/jampahlawan.png",
		"images/clock-sheet0.png",
		"images/bapaksoekarno-sheet0.png",
		"images/pause-sheet0.png",
		"images/tiledbackground.png",
		"images/love-sheet0.png",
		"images/jawaban-sheet0.png",
		"images/zz.png",
		"images/spritefont5.png",
		"images/ir_soekarnoremovebgpreview2-sheet0.png",
		"images/tiledbackground2.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/bawah-sheet0.png",
		"images/download-sheet0.png",
		"images/bendera_indoesiaremovebgpreview-sheet0.png",
		"images/f48fb1f6cffbecef5219d2fb06e95741removebgpreview-sheet0.png",
		"images/mentahanflagmlbb-sheet0.png",
		"images/brunei-sheet0.png",
		"images/brunei-sheet1.png",
		"images/brunei-sheet2.png",
		"images/rpl-sheet0.png",
		"images/smk-sheet0.png",
		"images/check_mark_and_cross_mark__error__correct_pngremovebgpreview-sheet0.png",
		"images/check_mark_and_cross_mark__error__correct_pngremovebgpreview-sheet1.png",
		"images/plainbrownbackground_brownwallpaper_chocolatebrown_plainbrown-sheet0.png",
		"media/kids happy funny background music for videos.m4a",
		"media/kids happy funny background music for videos.ogg",
		"media/funny comedy background music for videos.m4a",
		"media/funny comedy background music for videos.ogg",
		"media/suara efek centang ceklis.m4a",
		"media/suara efek centang ceklis.ogg",
		"media/wrong sound effect (sound effect salah).m4a",
		"media/wrong sound effect (sound effect salah).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}